import Vue from 'vue'
import {
  Switch,
  Button,
  Form,
  FormItem,
  Input,
  Message,
  Container,
  Header,
  Aside,
  Main,
  Menu,
  Submenu,
  MenuItem,
  Breadcrumb,
  BreadcrumbItem,
  Card,
  Row,
  Col,
  Table,
  TableColumn,
  Link,
  Tooltip,
  Pagination,
  Dialog,
  MessageBox,
  Radio,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Select,
  Option,
  DatePicker,
  Cascader,
  Autocomplete,
  RadioGroup,
  Steps,
  Step,
  Divider,
  Tabs,
  TabPane,
  Tree,
  Avatar,
  Carousel,
  CarouselItem,
  Image
} from 'element-ui'
Vue.use(Image)
Vue.use(CarouselItem)
Vue.use(Carousel)
Vue.use(Avatar)
Vue.use(Tree)
Vue.use(TabPane)
Vue.use(Tabs)
Vue.use(Divider)
Vue.use(Step)
Vue.use(Steps)
Vue.use(RadioGroup)
Vue.use(Switch)
Vue.use(Autocomplete)
Vue.use(Cascader)
Vue.use(DatePicker)
Vue.use(Option)
Vue.use(Select)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Dropdown)
Vue.use(Radio)
Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Menu)
Vue.use(Submenu)
Vue.use(MenuItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Link)
Vue.use(Tooltip)
Vue.use(Pagination)
Vue.use(Dialog)
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
